backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "about"
    label: "Sobre mí"
    files:
      - file: "content/authors/admin/_index.md"
        label: "Perfil"
        name: "perfil"
        fields:
          - {label: "Nombre", name: "title", widget: "string"}
          - {label: "Grado / Cargo", name: "role", widget: "string"}
          - {label: "Organización", name: "organization", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Biografía", name: "bio", widget: "text"}
